// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_ccmpp_tmb_TMBExports
#include <TMB.hpp>
#include "ccmpp_tmb.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "ccmpp_tmb") {
    return ccmpp_tmb(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
